### ISSUE TITLE
CRITICAL Sorry, Wpull unexpectedly crashed.

### ISSUE THREAD

**Issue by yi** [ludios/grab-site#148]
grab-site suddenly stop workings and no long work since then. 

I've tried uninstall-then-reinstall wpull and grab-site. But still not working.

Cry for help, please!

```
Traceback (most recent call last):
  File "/Users/aaa/gs-venv/lib/python3.7/site-packages/wpull/application/app.py", line 157, in run
    yield from pipeline.process()
  File "/Users/aaa/gs-venv/lib/python3.7/site-packages/wpull/pipeline/pipeline.py", line 194, in process
    yield from self._process_one_worker()
  File "/Users/aaa/gs-venv/lib/python3.7/site-packages/wpull/pipeline/pipeline.py", line 215, in _process_one_worker
    task.result()
  File "/Users/aaa/gs-venv/lib/python3.7/site-packages/wpull/pipeline/pipeline.py", line 119, in process
    item = yield from self.process_one(_worker_id=worker_id)
  File "/Users/aaa/gs-venv/lib/python3.7/site-packages/wpull/pipeline/pipeline.py", line 103, in process_one
    yield from task.process(item)
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/coroutines.py", line 120, in coro
    res = func(*args, **kw)
  File "/Users/aaa/gs-venv/lib/python3.7/site-packages/wpull/application/tasks/network.py", line 21, in process
    self._build_connection_pool(session)
  File "/Users/aaa/gs-venv/lib/python3.7/site-packages/wpull/application/tasks/network.py", line 85, in _build_connection_pool
    http_proxy = session.args.http_proxy.split(':', 1)
AttributeError: 'NoneType' object has no attribute 'split'
CRITICAL Sorry, Wpull unexpectedly crashed.
Disconnected from ws:// server: RuntimeError('Event loop is closed')
Exception ignored in: <coroutine object sender at 0x10e9d7ac8>
Traceback (most recent call last):
  File "/Users/aaa/gs-venv/lib/python3.7/site-packages/libgrabsite/dashboard_client.py", line 54, in sender
    await asyncio.sleep(delay)
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/tasks.py", line 566, in sleep
    future, result)
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 657, in call_later
    context=context)
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 667, in call_at
    self._check_closed()
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 480, in _check_closed
    raise RuntimeError('Event loop is closed')

```

**Comment by ivan** [comment]
That `http_proxy = session.args.http_proxy.split(':', 1)` makes me think something set an environmental variable to use an HTTP proxy.

Try `env | grep -i proxy` and maybe unset the variable?

Please let me know if it's not that.

**Comment by codsane** [comment]
I'm receiving an identical error after setting wpull's proxy using `--wpull-args="--http-proxy=\"0.0.0.0:1234\"`

Unfortunately `env | grep -i proxy` doesn't seem to return anything, and I've even made sure to run it within the container that grab-site is running in.

Even after removing `--wpull-args`, grab-site seems to be crashing with the same event loop error when attempting to crawl.
