### ISSUE TITLE
Crashes on Python 3.5

### ISSUE THREAD

**Issue by ivan** [ludios/grab-site#45]
via #archiveteam

```
Traceback (most recent call last):
  File "/home/sanky/.local/bin/grab-site", line 4, in <module>
    main.main()
  File "/home/sanky/.local/lib/python3.5/site-packages/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "/home/sanky/.local/lib/python3.5/site-packages/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/home/sanky/.local/lib/python3.5/site-packages/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/sanky/.local/lib/python3.5/site-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/home/sanky/.local/lib/python3.5/site-packages/libgrabsite/main.py", line 254, in main
    from wpull.app import Application
  File "/usr/lib/python3.5/site-packages/wpull/app.py", line 10, in <module>
    from trollius import From, Return
  File "/usr/lib/python3.5/site-packages/trollius/__init__.py", line 21, in <module>
    from .base_events import *
  File "/usr/lib/python3.5/site-packages/trollius/base_events.py", line 39, in <module>
    from . import coroutines
  File "/usr/lib/python3.5/site-packages/trollius/coroutines.py", line 15, in <module>
    from . import futures
  File "/usr/lib/python3.5/site-packages/trollius/futures.py", line 116, in <module>
    class Future(object):
  File "/usr/lib/python3.5/site-packages/trollius/futures.py", line 426, in Future
    __await__ = __iter__ # make compatible with 'await' expression
NameError: name '__iter__' is not defined
```

**Comment by ivan** [comment]
https://github.com/haypo/trollius/issues/4

@Sanqui

**Comment by ivan** [comment]
See #92
