### ISSUE TITLE
Upgrade to wpull 2.0

### ISSUE THREAD

**Issue by luckcolors** [ludios/grab-site#92]
```
Traceback (most recent call last):
  File "/usr/local/bin/grab-site", line 4, in <module>
    main.main()
  File "/usr/local/lib/python3.4/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.4/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.4/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/libgrabsite/main.py", line 359, in main
    from wpull.app import Application
ImportError: No module named 'wpull.app'
```

It seems that grab.site has some problem starting the latest version of wpull 2.0.1.
Wpull works if normally executed and works in archivebot.

**Comment by ivan** [comment]
Yeah, this just don't work work until I update grab-site for wpull 2.0.  I'm using https://github.com/ludios/grab-site/blob/ca7bc71045784b1cfda2a6d1d6dbc44a4000aa13/setup.py#L14 to lock the wpull version, but you can of course break grab-site by installing a newer wpull.  If you need to run both, you might be able to run grab-site in a virtualenv or a different user account.
